export default {
  SET_USER_LOGGED_IN: 'USER_LOGGED_IN',
  SET_IS_LOADING: 'SET_IS_LOADING',
  ADD_USER_DATA: 'ADD_USER_DATA',
  GET_APPLICATIONS: 'GET_APPLICATIONS',
  ADD_APPLICATION: 'ADD_APPLICATION',
  UPDATE_APPLICATION: 'UPDATE_APPLICATION',
  UPDATE_APPLICATION_STATUS: 'UPDATE_APPLICATION_STATUS',
  DELETE_APPLICATIONS: 'DELETE_APPLICATIONS',
};
